version: '3.1'

services:

  url_shortener:
    container_name: url_shortener
    image: golang:alpine3.16
    command: /bin/sh ./deployment/dev.sh
    working_dir: /go/src/url_shortener
    volumes:
      - ./:/go/src/url_shortener/
    ports:
      - "0.0.0.0:8080:8080"
    dns:
      - 8.8.8.8
    environment:
      - SERVER_ADDR=:8080
      #to enable TLS set the below variables
      - ENABLE_TLS=false
      - SSL_CRT_PATH=""
      - SSL_KEY_PATH=""
