basePath: /v1
definitions:
  http.GetTopDomainsErrorResponse:
    properties:
      error:
        type: string
      message:
        type: string
    type: object
  http.GetTopDomainsSuccessResponse:
    properties:
      data:
        additionalProperties:
          type: integer
        type: object
      message:
        type: string
    type: object
  http.ShortenURLErrorResponse:
    properties:
      error:
        type: string
      message:
        type: string
    type: object
  http.ShortenURLRequest:
    properties:
      url:
        type: string
    required:
      - url
    type: object
  http.ShortenURLSuccessResponse:
    properties:
      message:
        type: string
      short_url:
        type: string
    type: object
info:
  contact: {}
  title: URL SHORTENER
  version: "1.0"
paths:
  /{key}:
    get:
      description: Redirects the shortened URL to actual URL location
      parameters:
        - description: short url code
          in: path
          name: key
          required: true
          type: string
      responses:
        "301":
          description: Moved Permanently
        "500":
          description: Internal Server Error
          schema:
            $ref: "#/definitions/http.ShortenURLErrorResponse"
      summary: Redirector API
      tags:
        - URLShortener
  /metrics/domains/top:
    get:
      description: Returns a list of domains shortened maximum number of times
      parameters:
        - description: optional query param to specify how many domains to get
          in: query
          name: limit
          type: integer
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: "#/definitions/http.GetTopDomainsSuccessResponse"
        "500":
          description: Internal Server Error
          schema:
            $ref: "#/definitions/http.GetTopDomainsErrorResponse"
      summary: List Top Shortened Domains
      tags:
        - Metrics
  /url/shorten:
    post:
      description: Returns a shorten URL for input URL
      parameters:
        - description: json with actual url
          in: body
          name: request
          required: true
          schema:
            $ref: "#/definitions/http.ShortenURLRequest"
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: "#/definitions/http.ShortenURLSuccessResponse"
        "400":
          description: Bad Request
          schema:
            $ref: "#/definitions/http.ShortenURLErrorResponse"
        "500":
          description: Internal Server Error
          schema:
            $ref: "#/definitions/http.ShortenURLErrorResponse"
      summary: Shorten URL API
      tags:
        - URLShortener
swagger: "2.0"
